### ISSUE TITLE
Fora do AR

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [vmarcosp/covidbr-api#10]
Boa Tarde , esta fora do AR, que nao pode ser migrado para o Firebase ?

UTILIDADE PUBLICA !!

**Comment by vmarcosp** [comment]
Opa, obrigado por comunicar @GCPBigData.
Infelizmente ocorreram alguns problemas na nossa API e com a fonte de informações.
Já está tudo normalizado e funcionando normalmente.
Obrigado por comunidade :smile:
